# copied from https://github.com/VirtusLab/scala-cli/blob/b73b3e612eeba09c3231da9a51720cb8ddff1874/project/musl-image/Dockerfile
FROM messense/rust-musl-cross@sha256:47a3721b3e186abfd705feb1e03bf1d5212357ea26762cceef11530e0a2f2c7c
ADD setup.sh /setup.sh
RUN /setup.sh
